// S20: the tasks slice with Redux Toolkit. Same state shape and behaviour as S19; about half the code.
import { createSelector, createSlice, isAnyOf } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';
import type { Task } from '../../domain/types';
import { denormalize, normalize } from '../../domain/normalize';
import type { Normalized } from '../../domain/normalize';
import type { RootState } from '../../app/rootReducer';
import { loggedOut } from '../auth/authActions';
import {
  clearCompleted,
  deleteTask,
  fetchTasks,
  saveNewTask,
  saveTask,
  saveTaskChanges,
  toggleTaskOnServer,
} from './tasksThunks';

export type LoadStatus = 'idle' | 'loading' | 'succeeded' | 'failed';

/** Normalised since S19: `ids` keep the server's order, `entities` hold each task once. */
export interface TasksState extends Normalized<Task> {
  status: LoadStatus;
  error: string | null;
  /** RTK's `meta.requestId` of the fetch in flight; results of any other fetch are ignored (18.11). */
  currentRequestId: string | null;
  /** When the list was last loaded successfully (epoch ms), for "fetch if needed" (18.09). */
  fetchedAt: number | null;
}

export const initialTasksState: TasksState = {
  ids: [],
  entities: {},
  status: 'idle',
  error: null,
  currentRequestId: null,
  fetchedAt: null,
};

/** Insert or replace one task (Immer: mutate the draft). */
function upsert(state: TasksState, task: Task) {
  if (!state.entities[task.id]) state.ids.push(task.id);
  state.entities[task.id] = task;
}

function removeMany(state: TasksState, ids: readonly number[]) {
  for (const id of ids) delete state.entities[id];
  state.ids = state.ids.filter((id) => !ids.includes(id));
}

const tasksSlice = createSlice({
  name: 'tasks',
  initialState: initialTasksState,
  reducers: {
    /** A local event kept from S15 (the server marked all tasks done). `prepare` supplies the timestamp. */
    allCompleted: {
      reducer(state, action: PayloadAction<{ updatedAt: string }>) {
        for (const id of state.ids) {
          const task = state.entities[id];
          if (task && task.status !== 'DONE') {
            task.status = 'DONE'; // DONE tasks aren't touched, so Immer keeps their identity
            task.updatedAt = action.payload.updatedAt;
          }
        }
      },
      prepare(updatedAt: string = new Date().toISOString()) {
        return { payload: { updatedAt } };
      },
    },
  },
  extraReducers: (builder) => {
    builder
      // ── the list: pending / fulfilled / rejected, generated by createAsyncThunk ──
      .addCase(fetchTasks.pending, (state, action) => {
        state.status = 'loading'; // keep the current tasks visible while reloading
        state.error = null;
        state.currentRequestId = action.meta.requestId; // the NEWEST fetch wins
      })
      .addCase(fetchTasks.fulfilled, (state, action) => {
        if (action.meta.requestId !== state.currentRequestId) return; // stale: ignore (18.10)
        const { ids, entities } = normalize(action.payload.tasks);
        state.ids = ids;
        state.entities = entities;
        state.status = 'succeeded';
        state.currentRequestId = null;
        state.fetchedAt = action.payload.fetchedAt;
      })
      .addCase(fetchTasks.rejected, (state, action) => {
        if (action.meta.requestId !== state.currentRequestId) return;
        state.currentRequestId = null;
        if (action.meta.aborted || action.payload?.kind === 'cancelled') {
          state.status = state.fetchedAt === null ? 'idle' : 'succeeded'; // cancelled on purpose: not an error
          return;
        }
        state.status = 'failed';
        // rejectWithValue's payload carries the server's message; `error` only has a generic one (20.18)
        state.error = action.payload?.message ?? action.error.message ?? 'Unexpected error';
      })
      .addCase(deleteTask.fulfilled, (state, action) => removeMany(state, [action.payload]))
      .addCase(clearCompleted.fulfilled, (state, action) => removeMany(state, action.payload))
      .addCase(loggedOut, () => initialTasksState) // another user may log in next (15.10)
      // ── writes: every thunk whose fulfilled payload is a saved Task (isAnyOf matcher, 20.12) ──
      // (Matchers must come AFTER all addCase calls: the builder enforces that order.)
      .addMatcher(
        isAnyOf(saveNewTask.fulfilled, saveTask.fulfilled, saveTaskChanges.fulfilled, toggleTaskOnServer.fulfilled),
        (state, action) => upsert(state, action.payload),
      );
  },
});

export const { allCompleted } = tasksSlice.actions;
export const tasksReducer = tasksSlice.reducer;

// ── Selectors (unchanged from S19; createSelector now comes from @reduxjs/toolkit) ──
export const selectTaskIds = (state: RootState): number[] => state.tasks.ids;
export const selectTasksStatus = (state: RootState): LoadStatus => state.tasks.status;
export const selectTasksError = (state: RootState): string | null => state.tasks.error;

/** O(1) since S19: a lookup, not a search. */
export const selectTaskById = (state: RootState, id: number): Task | undefined => state.tasks.entities[id];

/** The tasks as an ordered array, memoised: the same array until `ids` or `entities` change (19.02). */
export const selectTasks = createSelector(
  [selectTaskIds, (state: RootState) => state.tasks.entities],
  (ids, entities) => denormalize({ ids, entities }),
);

/** Returns a number (a primitive), so `useSelector` can compare it with === safely (17.04). */
export const selectOpenTaskCount = (state: RootState): number =>
  selectTasks(state).filter((task) => task.status !== 'DONE').length;
